### ISSUE TITLE
Development plan / checklist

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/lib-gedcom#1]
- [X] Convert all encodings to UTF-8, including ANSEL
 - [ ] Convert inline sources to source objects
 - [ ] Convert inline media to media objects
 - [ ] Convert FamilyTreeMaker text files to GEDCOM
 - [ ] Handle lines containing XREFS at level > 0 (including on `CONC` and `CONT`)
